import React from "react";
import ServicePageTemplate from "@/components/ServicePageTemplate";

export default function CosmeticDermatologyPage() {
  return (
    <ServicePageTemplate
      title="Cosmetic Dermatology"
      subtitle="Advanced Aesthetic Treatments for Natural-Looking Rejuvenation"
      description="Cosmetic dermatology combines medical expertise with aesthetic artistry to enhance your natural beauty. At Dermaglare Skin, Dr. Jabu Nkehli offers evidence-based cosmetic treatments that deliver visible results while maintaining skin health. From injectable treatments like Botox to advanced skin rejuvenation procedures including chemical peels, micro-needling, PRP therapy, and skin tightening, we provide comprehensive aesthetic solutions tailored to your unique goals. As a specialist dermatologist, Dr. Nkehli understands skin anatomy, aging processes, and safe treatment protocols, ensuring you receive expert care that looks natural and enhances your confidence."
      heroImage="https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1200&q=80"
      sideImage="https://images.unsplash.com/photo-1596178060810-7e547b5b8b1b?w=800&q=80"
      sections={[
        {
          title: "What is Cosmetic Dermatology?",
          content:
            "Cosmetic dermatology focuses on improving the appearance of skin, hair, and nails using medical treatments and procedures. Unlike cosmetic surgery which involves major operations and general anesthesia, cosmetic dermatology procedures are typically minimally invasive, performed in-office with little to no downtime. KEY PRINCIPLES: Evidence-based treatments with proven safety and efficacy, medical-grade products and technologies, procedures performed by trained specialist dermatologist, natural-looking results that enhance rather than change appearance, and combination treatments for comprehensive rejuvenation. COMMON GOALS: Reduce visible signs of aging (fine lines, wrinkles, volume loss), improve skin tone and texture, minimize acne scars and other scarring, address pigmentation concerns (sun spots, melasma), tighten loose or sagging skin, restore facial volume and contours, and prevent future aging with proactive treatments. What sets cosmetic dermatology apart is the medical expertise behind aesthetic treatments. Dr. Nkehli's understanding of skin physiology, wound healing, and potential complications ensures safe, effective treatments customized to your skin type, concerns, and aesthetic goals.",
        },
        {
          title: "Anti-Aging Injectable Treatments",
          content:
            "Injectable treatments are among the most popular and effective cosmetic dermatology procedures. Dr. Nkehli offers expert injection techniques for natural-looking rejuvenation. BOTOX (BOTULINUM TOXIN): Temporarily relaxes muscles that cause dynamic wrinkles, smooths forehead lines, frown lines between eyebrows, and crow's feet, preventive treatment when started in 20s-30s, results visible within 3-7 days and last 3-4 months, safe when administered by trained specialist, and natural-looking results without frozen appearance. TREATMENT AREAS: Forehead horizontal lines, glabellar lines (11s between eyebrows), crow's feet around eyes, bunny lines on nose, gummy smile correction, chin dimpling, neck bands (platysma), and hyperhidrosis (excessive underarm sweating). Dr. Nkehli's expert injection technique ensures symmetrical, natural results that soften wrinkles while maintaining facial expression. The goal is to look refreshed and relaxed, not frozen or overdone. For detailed information about Botox treatments, applications, what to expect, and pricing, visit our dedicated Botox service page.",
        },
        {
          title: "Chemical Peels for Skin Rejuvenation",
          content:
            "Chemical peels use controlled exfoliation to improve skin tone, texture, and appearance. Dr. Nkehli offers various peel depths customized to your specific concerns. SUPERFICIAL PEELS: Light exfoliation of outermost skin layer, minimal downtime with mild flaking, improve dullness and fine texture issues, brighten complexion and even skin tone, can be repeated every 2-4 weeks, and suitable for all skin types including darker skin. MEDIUM PEELS: Penetrate to mid-dermal layers, address moderate sun damage and pigmentation, improve fine lines and texture concerns, downtime of 3-7 days with visible peeling, results more dramatic than superficial peels, and typically repeated every 3-6 months. DEEPER PEELS: Significant exfoliation for advanced concerns, address deep wrinkles and significant sun damage, more intensive recovery period, dramatic results with substantial improvement, performed less frequently, and requires careful patient selection. CONDITIONS TREATED: Sun damage and photoaging, hyperpigmentation and melasma, fine lines and mild wrinkles, acne and post-acne marks, rough skin texture, large pores and blackheads, and dull, tired-looking skin. Chemical peels can be customized to your skin type, concerns, and tolerance for downtime. See our Chemical Peeling service page for detailed information about peel types, recovery, expected results, and pricing.",
        },
        {
          title: "Micro-Needling and Collagen Induction Therapy",
          content:
            "Micro-needling creates controlled micro-injuries that stimulate your skin's natural healing response, triggering collagen and elastin production. THE TREATMENT: Medical-grade micro-needling device with fine needles, controlled puncture depth based on treatment area and concern, stimulates collagen and elastin production, improves skin texture and firmness, minimal downtime with redness for 1-3 days, and series of 3-6 treatments for optimal results. CONDITIONS TREATED: Acne scars and other scarring, fine lines and wrinkles, enlarged pores, rough skin texture, mild skin laxity, stretch marks, and uneven skin tone. VAMPIRE FACIAL (PRP + MICRO-NEEDLING): Combination treatment for enhanced results, your own platelet-rich plasma applied during micro-needling, growth factors accelerate healing and collagen production, natural approach using your body's healing factors, and superior results compared to micro-needling alone. Micro-needling is safe for all skin types and provides gradual, natural improvement in skin quality. For detailed information about the procedure, recovery, results timeline, and pricing, visit our Micro-Needling service page.",
        },
        {
          title: "Platelet-Rich Plasma (PRP) Therapy",
          content:
            "PRP therapy harnesses your body's natural growth factors to rejuvenate skin and stimulate hair growth. This natural, biocompatible treatment offers impressive results. PRP FOR FACIAL REJUVENATION: Blood draw and processing to concentrate platelets, platelet-rich plasma contains growth factors, combined with micro-needling (Vampire Facial) or injected into skin, stimulates collagen production and cellular renewal, improves skin tone, texture, and firmness, and natural results that develop over weeks to months. PRP FOR HAIR RESTORATION: Effective treatment for androgenetic alopecia (pattern hair loss), injected into scalp in areas of thinning, stimulates dormant hair follicles, increases hair thickness and density, series of treatments with maintenance sessions, and natural approach without medications. BENEFITS: Uses your own blood (no foreign substances), minimal risk of allergic reaction or rejection, natural-looking gradual results, can be combined with other treatments, and minimal downtime. PRP therapy is particularly appealing to patients seeking natural approaches to anti-aging and hair restoration. For comprehensive information about PRP applications, treatment protocols, results, and pricing, see our dedicated PRP service page.",
        },
        {
          title: "Skin Tightening and Body Contouring",
          content:
            "Non-invasive skin tightening treatments use advanced technologies to firm loose or sagging skin without surgery. RADIOFREQUENCY (RF) SKIN TIGHTENING: Heat energy delivered to deeper skin layers, stimulates collagen production and contraction, tightens loose skin on face and body, comfortable treatment with no downtime, and gradual improvement over 2-6 months. ACOUSTIC WAVE THERAPY: Uses sound waves to stimulate collagen, improves skin texture and firmness, effective for cellulite and localized fat, comfortable treatment with immediate return to activities, and series of treatments for optimal results. TREATMENT AREAS: Face and jawline (improve jowls and sagging), neck and décolletage, arms (bat wing tightening), abdomen (post-pregnancy or weight loss), thighs (cellulite and skin texture), and buttocks. IDEAL CANDIDATES: Mild to moderate skin laxity, realistic expectations about results, not a replacement for surgical facelift in severe laxity, those seeking gradual natural improvement without surgery, and willing to complete series of treatments. Non-invasive skin tightening provides significant improvement for appropriate candidates without the risks, cost, and recovery of surgery. Visit our Skin Tightening service page for detailed information about technologies, treatment protocols, expected results, and pricing.",
        },
        {
          title: "Comprehensive Facial Rejuvenation",
          content:
            "The most dramatic and natural results often come from combining complementary treatments that address different aspects of aging. DR. NKEHLI'S COMBINATION APPROACH: Botox to relax dynamic wrinkles, chemical peels or micro-needling to improve texture and tone, PRP to stimulate collagen and cellular renewal, skin tightening for firmness and lift, and medical-grade skincare to maintain results. CUSTOMIZED TREATMENT PLANS: Comprehensive facial assessment of your concerns, discussion of your aesthetic goals and budget, recommendation of treatments with most impact, sequencing of procedures for optimal results, and realistic timeline and expectations. NATURAL-LOOKING RESULTS: Subtle enhancements that don't look done, preservation of facial character and expression, gradual improvement that others notice but can't pinpoint, no telltale signs of treatments, and refreshed, rested appearance. MAINTENANCE PROGRAMS: Regular treatment schedule to maintain results, adjustment of treatments as aging continues, proactive approach to prevent new aging signs, and long-term relationship with expert provider. Combination treatments provide comprehensive rejuvenation that addresses the multiple factors contributing to an aged appearance, resulting in more dramatic yet natural-looking transformation than any single treatment alone.",
        },
        {
          title: "Acne Scar Treatment",
          content:
            "Acne scars can significantly impact self-confidence. Dr. Nkehli offers multiple treatments to improve acne scarring and restore smooth skin. TYPES OF ACNE SCARS: Atrophic scars (depressed scars including icepick, boxcar, and rolling scars), hypertrophic scars (raised, thickened scars), post-inflammatory hyperpigmentation (dark marks, not true scars), and combination of scar types requiring multimodal treatment. TREATMENT OPTIONS: Micro-needling with PRP (stimulates collagen, fills depressed scars, improves texture), chemical peels (improve superficial scarring and pigmentation, even skin tone), subcision (releases tethered scars, allows filling from beneath), dermal fillers for select deeper scars, and combination treatments for best results. TREATMENT PROTOCOL: Initial assessment of scar types and severity, customized treatment plan based on your specific scarring, series of treatments spaced weeks apart, gradual improvement over several months, and realistic expectations (significant improvement but not perfection). PREVENTION: Treatment of active acne to prevent new scarring, avoiding picking and squeezing, early intervention for severe acne, and consistent skincare routine. Acne scars require patience and commitment to a treatment series, but significant improvement is possible with appropriate combination therapy under expert care.",
        },
        {
          title: "Pigmentation Treatment",
          content:
            "Uneven pigmentation, dark spots, and melasma are common concerns that can be effectively treated. PIGMENTATION CONCERNS: Sun spots and age spots (solar lentigines), melasma (hormone-related dark patches, especially on face), post-inflammatory hyperpigmentation (dark marks after acne, injury, or inflammation), and uneven skin tone from cumulative sun damage. TREATMENT OPTIONS: Chemical peels (exfoliate darkened surface skin, lighten pigmentation over series), prescription lightening agents (hydroquinone, kojic acid, retinoids, vitamin C), chemical peels targeting pigmentation, sun protection (essential to prevent worsening), and combination approach for stubborn pigmentation like melasma. MELASMA MANAGEMENT: Notoriously difficult to treat and prone to recurrence, requires ongoing maintenance, strict sun protection essential, hormonal triggers (pregnancy, birth control), treatment plan may include lightening agents, chemical peels, and sun protection. REALISTIC EXPECTATIONS: Gradual improvement over weeks to months, may require maintenance treatments, pigmentation can recur with sun exposure, sun protection non-negotiable for lasting results, and deeper pigmentation more challenging to treat. Treating pigmentation requires patience and commitment to sun protection, but Dr. Nkehli's comprehensive approach can provide significant improvement and prevent new dark spots from forming.",
        },
        {
          title: "Medical-Grade Skincare",
          content:
            "Professional skincare products are an essential component of any cosmetic dermatology program. Dr. Nkehli recommends and provides medical-grade products that complement your treatments. DIFFERENCE FROM OVER-THE-COUNTER: Higher concentrations of active ingredients, pharmaceutical-grade quality and purity, proven effectiveness through clinical studies, stable formulations that penetrate skin effectively, and available only through medical professionals. KEY INGREDIENTS: Retinoids (prescription-strength vitamin A for anti-aging, acne, and texture), vitamin C (antioxidant for brightening and collagen production), growth factors (stimulate cellular renewal), peptides (support collagen production), hyaluronic acid (intense hydration), and niacinamide (improves texture, tone, and pore appearance). BASIC ANTI-AGING REGIMEN: Gentle cleanser morning and evening, antioxidant serum (vitamin C) in morning, retinoid product in evening, moisturizer appropriate for skin type, and broad-spectrum SPF 30+ sunscreen every morning. CUSTOMIZATION: Products selected for your specific skin type, address your particular concerns, compatible with any treatments you receive, and instruction on proper use for safety and effectiveness. Professional skincare extends and enhances results from in-office procedures while preventing future aging. Dr. Nkehli provides specific product recommendations during your consultation.",
        },
        {
          title: "Why Choose Dr. Nkehli for Cosmetic Dermatology?",
          content:
            "Cosmetic dermatology requires medical expertise, aesthetic sense, and refined technique. Dr. Nkehli offers all three. MEDICAL EXPERTISE: Specialist dermatologist with extensive training, deep understanding of skin anatomy and physiology, knowledge of treatment safety and potential complications, ability to recognize and manage adverse reactions, and appropriate patient selection for procedures. AESTHETIC ARTISTRY: Natural-looking results as priority, understanding of facial aesthetics and proportions, customization to your unique features, conservative approach that can be built upon, and subtle enhancements that improve without transforming. COMPREHENSIVE CARE: Full range of cosmetic dermatology treatments, combination treatment plans for optimal results, medical-grade skincare recommendations, ongoing relationship for maintenance, and treatment of any medical skin concerns alongside cosmetic care. PATIENT-CENTERED APPROACH: Listening to your goals and concerns, realistic discussion of expected outcomes, transparent about limitations of treatments, no pressure for unnecessary procedures, and partnership in your aesthetic journey. Choosing a specialist dermatologist for cosmetic treatments ensures you receive safe, effective care with natural-looking results. Dr. Nkehli's combination of medical knowledge and aesthetic expertise provides the highest level of cosmetic dermatology care.",
        },
        {
          title: "Consultation and Treatment Planning",
          content:
            "Your cosmetic dermatology journey begins with a comprehensive consultation to develop a personalized treatment plan. THE CONSULTATION: Discussion of your aesthetic concerns and goals, assessment of your skin condition and aging patterns, explanation of treatment options suitable for your concerns, realistic discussion of expected results and limitations, treatment timeline and sequencing if multiple procedures, pricing for recommended treatments, and time for all your questions. WHAT TO EXPECT: Arrive with clean face (no makeup if possible), honest discussion of your concerns and goals, review of medical history and current medications, photos for your medical record and tracking progress, and written treatment plan and cost estimate. DECISION MAKING: No pressure to decide immediately, take time to consider recommendations, return for treatment when ready, financing options available if needed, and we're here to answer questions as they arise. BEGINNING TREATMENT: Some treatments can be started same day as consultation, others scheduled for separate appointment, detailed pre-treatment and post-treatment instructions provided, and follow-up appointments scheduled as needed. Contact Dermaglare Skin today to schedule your cosmetic dermatology consultation with Dr. Jabu Nkehli. Together, you'll develop a personalized plan to help you achieve your aesthetic goals with natural-looking, confidence-enhancing results.",
        },
      ]}
      features={[
        "Botox Injections",
        "Micro-needling",
        "Platelet-Rich Plasma (PRP)",
        "Chemical Peels",
        "Skin Tightening",
        "Acne Scar Treatment",
        "Pigmentation Treatment",
        "Medical-Grade Skincare",
      ]}
    />
  );
}
