import React from "react";
import ServicePageTemplate from "@/components/ServicePageTemplate";

export default function PaediatricDermatologyPage() {
  return (
    <ServicePageTemplate
      heroImage="https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=1200&q=80"
      sideImage="https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&q=80"
      title="Paediatric Dermatology"
      subtitle="Expert, Compassionate Dermatology Care for Children and Adolescents"
      description="Pediatric dermatology focuses on the diagnosis and treatment of skin, hair, and nail conditions in infants, children, and adolescents. Children's skin has unique characteristics and responds differently to treatments than adult skin, requiring specialized knowledge and gentle approaches. At Dermaglare Skin, Dr. Jabu Nkehli provides expert, compassionate care for young patients from newborns through teenagers. With extensive experience treating childhood skin conditions and a gentle, child-friendly approach, she puts both children and parents at ease while delivering effective treatment for conditions ranging from common diaper rash and eczema to more complex birthmarks, genetic conditions, and adolescent acne."
      sections={[
        {
          title: "Why Pediatric Dermatology Requires Specialized Care",
          content:
            "Children are not simply small adults—their skin has unique characteristics requiring specialized knowledge and treatment approaches. DIFFERENCES IN CHILDREN'S SKIN: Thinner epidermis with increased absorption of topical medications (requiring adjusted dosing and careful product selection), immature immune system affecting susceptibility to infections, different distribution of sweat glands and oil glands, higher surface area to body weight ratio (systemic effects from topical treatments more likely), and ongoing development requiring monitoring of treatment effects on growth. UNIQUE CONSIDERATIONS: Age-appropriate communication with child and family, gentle examination techniques to minimize anxiety, treatment plans considering child's development stage, formulations and dosages adjusted for pediatric use, safety profile of medications in children, impact on school attendance and social development, and parent education and involvement in treatment. AGE-SPECIFIC CONCERNS: Newborns (normal newborn rashes, birthmarks, hemangiomas), infants (eczema, diaper dermatitis, cradle cap), young children (viral exanthems, warts, molluscum), school-age (impetigo, tinea infections, atopic dermatitis), and adolescents (acne, hirsutism, body image concerns). Dr. Nkehli's experience and gentle approach ensure children receive appropriate, effective care in a comfortable, supportive environment.",
        },
        {
          title: "Common Pediatric Skin Conditions",
          content:
            "Children experience a wide range of skin conditions, some unique to childhood and others similar to adult conditions but requiring age-appropriate treatment. INFANT CONDITIONS: Diaper dermatitis (diaper rash from moisture and irritation), cradle cap (seborrheic dermatitis of scalp), baby acne (neonatal and infantile acne), milia (tiny white bumps on newborn faces), erythema toxicum (common benign newborn rash), and infantile hemangiomas (strawberry birthmarks). ECZEMA/ATOPIC DERMATITIS: Very common in childhood (affects up to 20% of children), typically begins in infancy, characterized by itchy, dry, red patches, often on face, scalp, and extensor surfaces in infants, flexural areas (inner elbows, behind knees) in older children, and requires ongoing management with moisturizers, gentle skincare, and medication during flares. INFECTIOUS CONDITIONS: Impetigo (bacterial infection with honey-colored crusting), molluscum contagiosum (viral infection with pearl-like bumps), warts (common on hands and feet), tinea infections (ringworm, athlete's foot), hand-foot-mouth disease, and chickenpox (now less common due to vaccination). ALLERGIC CONDITIONS: Contact dermatitis (from irritants or allergens), urticaria (hives from allergic reactions), and atopic dermatitis (eczema with allergic component). These conditions range from self-limited to chronic, requiring accurate diagnosis and appropriate treatment.",
        },
        {
          title: "Newborn Skin Care and Birthmarks",
          content:
            "The newborn period involves unique skin concerns and normal variations that can worry new parents. Dr. Nkehli provides expert evaluation and reassurance. NORMAL NEWBORN FINDINGS: Erythema toxicum (blotchy red rash with white/yellow bumps, appears day 2-5, resolves on its own), milia (tiny white bumps on face from trapped keratin, resolve spontaneously), neonatal acne (small red bumps on face, resolves without treatment), mongolian spots (blue-gray birthmarks on lower back, common in darker-skinned infants), and salmon patches (pink patches on eyelids, forehead, or nape, often fade). BIRTHMARKS REQUIRING EVALUATION: Infantile hemangiomas (strawberry marks that grow then involute, some require treatment if near eyes, nose, mouth, or in beard distribution), port-wine stains (flat red/purple vascular birthmarks, permanent without treatment, laser treatment available), congenital melanocytic nevi (brown moles present at birth, larger ones require monitoring), and café-au-lait macules (light brown patches, multiple spots may indicate genetic syndromes). WHEN TREATMENT NEEDED: Hemangiomas in critical locations affecting vision, breathing, or feeding, rapidly growing hemangiomas, ulcerated hemangiomas (painful, risk of infection and scarring), port-wine stains (laser treatment most effective when started early), and large or concerning moles. Dr. Nkehli examines newborns to distinguish normal findings from those requiring monitoring or treatment, providing parents with education and peace of mind.",
        },
        {
          title: "Eczema and Atopic Dermatitis in Children",
          content:
            "Eczema (atopic dermatitis) is one of the most common chronic conditions in childhood, requiring ongoing management. ABOUT CHILDHOOD ECZEMA: Often begins in infancy (2-6 months), genetic predisposition with family history of eczema, asthma, or allergies, characterized by dry, itchy, red, inflamed patches, distribution changes with age (face and extensor surfaces in infants, flexural areas in older children), and waxing and waning course with flares and remissions. TRIGGERS: Dry skin and low humidity, irritants (soaps, detergents, wool clothing), allergens (foods, environmental), infections (bacterial, viral), temperature extremes, sweating, and stress. MANAGEMENT APPROACH: Daily moisturization with thick creams or ointments, gentle skincare (mild cleansers, lukewarm baths, pat dry), avoidance of known triggers, topical corticosteroids for flares (age-appropriate potency), topical calcineurin inhibitors for sensitive areas, wet wrap therapy for severe flares, treatment of secondary infections, and antihistamines for itching at night. LONG-TERM OUTLOOK: Many children outgrow eczema by school age, some continue with milder symptoms into adulthood, proactive management prevents complications (infection, scarring, sleep disruption), and parent education essential for effective management. Dr. Nkehli works with families to develop individualized eczema management plans that control symptoms while minimizing medication use.",
        },
        {
          title: "Warts, Molluscum, and Viral Skin Conditions",
          content:
            "Viral skin infections are common in childhood and often spread in school or daycare settings. WARTS (VERRUCAE): Caused by human papillomavirus (HPV), common on hands, feet, and around nails, spread by direct contact and autoinoculation, can persist for years if untreated, and various treatment options available. TREATMENT OPTIONS: Watchful waiting (many resolve spontaneously over 1-2 years), cryotherapy with liquid nitrogen (freezing, requires cooperation from child), topical salicylic acid (home treatment, gradual resolution), cantharidin (blister-inducing agent, office application), and other options for resistant warts. MOLLUSCUM CONTAGIOSUM: Viral infection causing small pearl-like bumps with central dimple, very common in childhood (up to 10% of children), spread by direct contact and fomites, can spread on child's own body by scratching, and typically self-limited but can persist 6-18 months. TREATMENT APPROACH: Watchful waiting (most resolve on their own), cryotherapy for bothersome lesions, topical medications, curettage (removal with small instrument), prevention of spread (avoid sharing towels, covering lesions), and treatment of dermatitis around lesions. OTHER VIRAL CONDITIONS: Hand-foot-mouth disease (coxsackievirus), chickenpox (varicella, now less common with vaccination), and molluscum-like lesions require accurate diagnosis. Dr. Nkehli helps parents understand these common viral conditions, when treatment is beneficial versus watchful waiting, and how to prevent spread to others.",
        },
        {
          title: "Adolescent Acne",
          content:
            "Acne is extremely common in adolescence, affecting up to 85% of teenagers. Early treatment prevents scarring and psychological impact. CAUSES: Hormonal changes of puberty stimulating oil gland activity, increased sebum production, follicular plugging (blackheads and whiteheads), Cutibacterium acnes bacteria proliferation, and inflammation. TYPES: Comedonal acne (mainly blackheads and whiteheads), inflammatory acne (red bumps and pustules), nodulocystic acne (deep, painful cysts), and combination types. TREATMENT BASED ON SEVERITY: MILD ACNE: Topical retinoids (vitamin A derivatives, unclog pores), benzoyl peroxide (antibacterial), combination products, and consistent daily skincare routine. MODERATE ACNE: Topical combination therapy, oral antibiotics (short-term for inflammatory acne), hormonal therapy for females (birth control pills for hormonal acne), and regular follow-up to adjust treatment. SEVERE ACNE: Oral isotretinoin (Accutane) for severe nodulocystic acne, requires monitoring and pregnancy prevention, highly effective with potential for permanent clearance, and specialist dermatologist supervision essential. ACNE SCARRING PREVENTION: Early aggressive treatment of acne, avoiding picking and squeezing, treatment of active breakouts promptly, and scar treatment options if scarring occurs (micro-needling, chemical peels, PRP). PSYCHOSOCIAL IMPACT: Acne significantly affects self-esteem during vulnerable teenage years, can lead to social withdrawal and depression, and treating acne improves quality of life and confidence. Dr. Nkehli understands the importance of clear skin to teenagers and provides effective, personalized acne treatment with compassion and without judgment.",
        },
        {
          title: "Hair and Scalp Conditions in Children",
          content:
            "Hair and scalp problems in children range from benign conditions to those requiring treatment. COMMON CONDITIONS: Cradle cap (infantile seborrheic dermatitis, yellow greasy scales on scalp, treated with gentle cleansing and oil), tinea capitis (scalp ringworm, requires oral antifungal medication, can cause hair loss and scarring if not treated), alopecia areata (autoimmune hair loss causing round bald patches, various treatment options, often regrows spontaneously), telogen effluvium (diffuse hair shedding after illness, stress, surgery, typically regrows in months), trichotillomania (hair pulling habit, behavioral intervention needed), and pediculosis capitis (head lice, common in school-age children). HAIR LOSS IN CHILDREN: Always requires evaluation to determine cause, different causes have different treatments, may indicate underlying medical condition, and psychological impact requiring sensitive approach. TREATMENT APPROACHES: Topical medications for scalp conditions, oral medications when needed (antifungals for ringworm), corticosteroid injections for alopecia areata in some cases, counseling for hair pulling habits, and parent education about hair care. Dr. Nkehli provides thorough evaluation of hair and scalp concerns with appropriate investigation and treatment to restore normal hair growth when possible.",
        },
        {
          title: "Treatment Approaches for Children",
          content:
            "Treating children requires special considerations regarding safety, efficacy, and acceptability. MEDICATION SAFETY: Age-appropriate formulations and dosing, medications with proven safety in children, avoidance of medications contraindicated in pediatrics, monitoring for side effects, and consideration of systemic absorption from topical treatments. GENTLE PROCEDURES: Cryotherapy (liquid nitrogen) for appropriate lesions, topical anesthetics before painful procedures, curettage for molluscum or small lesions, patch testing for allergic contact dermatitis, and child-friendly approach to minimize anxiety. BEHAVIORAL STRATEGIES: Age-appropriate explanations of procedures, distraction techniques during treatments, positive reinforcement, parent presence for comfort, and building trust for ongoing care. SYSTEMIC TREATMENTS WHEN NEEDED: Oral antibiotics for infections or inflammatory acne, oral antifungals for stubborn fungal infections, antihistamines for allergic conditions, and specialized medications under close supervision. PHOTOTHERAPY: Light therapy for severe eczema, psoriasis, or other conditions, safe and effective when properly administered, and requires series of treatments. Dr. Nkehli carefully selects treatments that are safe, effective, and acceptable for children and families, always starting with gentlest approaches and escalating only when necessary.",
        },
        {
          title: "Parent Education and Home Care",
          content:
            "Successful management of childhood skin conditions requires parent education and consistent home care. SKINCARE BASICS: Gentle, fragrance-free cleansers appropriate for children, lukewarm water for bathing (not hot), limiting bath time to 5-10 minutes, immediate moisturization after bathing while skin still damp, and fragrance-free, hypoallergenic moisturizers. ECZEMA MANAGEMENT AT HOME: Multiple daily moisturization (3-4 times), identifying and avoiding triggers, proper use of prescription medications, wet wrap therapy for severe flares, maintaining comfortable home humidity, and cotton clothing to minimize irritation. MEDICATION APPLICATION: Proper technique for topical application, appropriate amount to use, frequency and duration of use, where to apply (affected areas only versus wider area), and when to call if not improving. SUN PROTECTION: Essential for all children, especially with certain conditions, broad-spectrum SPF 30+ sunscreen, sun-protective clothing and hats, avoiding peak sun hours (10 AM - 4 PM), and reapplication every 2 hours. WHEN TO CALL: Signs of infection (increasing pain, pus, fever, spreading redness), severe flare not responding to usual treatment, adverse reaction to medication, and concerns about treatment response. Dr. Nkehli ensures parents understand their child's condition and feel confident managing it at home with clear written instructions and accessible follow-up.",
        },
        {
          title: "Why Choose Dr. Nkehli for Your Child's Skin Care",
          content:
            "Choosing the right dermatologist for your child ensures accurate diagnosis and appropriate, gentle treatment. SPECIALIZED EXPERTISE: Specialist dermatologist with experience treating children, understanding of pediatric skin conditions and their management, knowledge of age-appropriate medications and dosing, ability to distinguish normal variations from pathology, and awareness of conditions unique to childhood. GENTLE, CHILD-FRIENDLY APPROACH: Warm, compassionate manner that puts children at ease, age-appropriate communication with child, involvement of parents in decision-making, minimization of child's anxiety and discomfort, and building trust for ongoing care. COMPREHENSIVE EVALUATION: Thorough history and gentle examination, accurate diagnosis with appropriate testing when needed, treatment plans considering child's age and development, education for both child (when appropriate) and parents, and follow-up to ensure treatment success. PARENT PARTNERSHIP: Recognition of parent as expert on their child, listening to parent concerns and observations, shared decision-making about treatment, accessibility for questions and concerns, and support throughout treatment journey. Dr. Nkehli treats each child with kindness and respect, ensuring they receive expert care in a supportive environment while helping parents feel confident managing their child's skin condition.",
        },
        {
          title: "Scheduling Your Child's Appointment",
          content:
            "If your child has a skin concern, schedule a consultation with Dr. Nkehli for expert evaluation and treatment. PREPARING FOR THE VISIT: Make note of when symptoms started and any changes, list of triggers or factors that worsen condition, bring current medications and products used on child's skin, photos of condition at different stages if available, and prepare list of questions. WHAT TO EXPECT: Gentle, child-friendly examination, thorough discussion of diagnosis, explanation of treatment options, written treatment instructions, and time for all your questions. BRINGING YOUR CHILD: Bring comfort items if child is anxious (favorite toy, blanket), arrive a few minutes early to settle in, you can stay with child throughout appointment, and positive attitude helps child feel at ease. FOLLOW-UP CARE: Schedule determined by condition being treated, close monitoring to ensure treatment effectiveness, adjustment of treatment plan if needed, and ongoing partnership in your child's skin health. PRICING: Consultation fees apply, treatment costs discussed during visit, and many medical conditions covered by insurance. Contact Dermaglare Skin today to schedule a pediatric dermatology appointment. Dr. Jabu Nkehli looks forward to helping your child achieve healthy, comfortable skin with gentle, expert care that puts both children and parents at ease.",
        },
      ]}
      features={[
        "Eczema & Atopic Dermatitis",
        "Infant Skin Conditions",
        "Birthmark Evaluation",
        "Adolescent Acne",
        "Warts & Molluscum",
        "Hair & Scalp Disorders",
        "Allergic Skin Conditions",
        "Gentle Treatment Approaches",
      ]}
    />
  );
}
