import React from "react";
import ServicePageTemplate from "@/components/ServicePageTemplate";

export default function SurgicalDermatologyPage() {
  return (
    <ServicePageTemplate
      heroImage="https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=1200&q=80"
      sideImage="https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&q=80"
      title="Surgical Dermatology"
      subtitle="Expert Surgical Procedures for Skin Disease Diagnosis and Treatment"
      description="Surgical dermatology encompasses the diagnosis and treatment of skin conditions through surgical procedures. As a specialist dermatologist, Dr. Jabu Nkehli is trained in a comprehensive range of surgical techniques, from simple biopsies to excision of skin cancers and removal of benign lesions. These procedures are performed with precision in our office setting under local anesthesia, ensuring optimal outcomes with minimal scarring. Whether you need a diagnostic biopsy, removal of a suspicious lesion, or excision of a bothersome growth, Dr. Nkehli provides expert surgical care with compassion and attention to detail."
      sections={[
        {
          title: "What is Surgical Dermatology?",
          content:
            "Surgical dermatology involves performing procedures to diagnose and treat skin conditions through surgical intervention. Unlike cosmetic procedures aimed purely at appearance, surgical dermatology addresses medical concerns including skin cancer diagnosis and treatment, removal of precancerous lesions, excision of benign growths causing symptoms, diagnostic biopsies for unclear conditions, and treatment of cysts, lipomas, and other skin lesions. Dr. Nkehli's training as a specialist dermatologist includes extensive surgical expertise in skin anatomy, surgical techniques that minimize scarring, proper wound closure and repair, management of bleeding and complications, and post-operative care for optimal healing. Most dermatologic surgical procedures are performed in the office under local anesthesia, allowing you to return home the same day with minimal disruption to your routine. The combination of medical and surgical expertise ensures accurate diagnosis and appropriate treatment with the best possible cosmetic outcome.",
        },
        {
          title: "Skin Biopsies",
          content:
            "Skin biopsy is one of the most important diagnostic tools in dermatology, allowing definitive diagnosis through microscopic examination of tissue. TYPES OF BIOPSIES: Shave biopsy (removes superficial skin layers for raised lesions, quick procedure with minimal scarring, suitable for many benign growths and some skin cancers), Punch biopsy (circular blade removes deeper tissue sample, 2-8mm diameter, typically requires 1-2 stitches, ideal for inflammatory conditions and deep lesions), Excisional biopsy (complete removal of entire lesion with margin, requires stitches for closure, provides definitive diagnosis and treatment simultaneously), and Incisional biopsy (sample from larger lesion when complete removal not initially indicated). THE BIOPSY PROCESS: Local anesthesia injection (brief stinging sensation), tissue removal (typically painless once numb), hemostasis (controlling any bleeding), wound closure (stitches, cautery, or healing by itself depending on type), and tissue sent to pathology laboratory for analysis. RESULTS: Pathology results typically available in 5-10 business days, Dr. Nkehli reviews all results personally, results discussion and treatment recommendations provided, further treatment planned based on diagnosis. Biopsies are essential for diagnosing suspicious lesions, confirming skin cancer, identifying inflammatory conditions, and guiding treatment decisions.",
        },
        {
          title: "Skin Cancer Excision",
          content:
            "When skin cancer is diagnosed, surgical excision is often the definitive treatment. Dr. Nkehli performs surgical removal of skin cancers with appropriate margins to ensure complete removal while minimizing scarring. TYPES OF SKIN CANCER TREATED: Basal Cell Carcinoma (most common, rarely metastasizes, excellent cure rates with proper excision), Squamous Cell Carcinoma (second most common, can spread if not treated, requires adequate margins), Melanoma (most serious, requires wider margins, coordination with oncology team for advanced cases), and precancerous lesions (actinic keratoses, in situ cancers). THE EXCISION PROCESS: Pre-operative markings (planned excision with appropriate margin based on cancer type and size), local anesthesia (ensuring complete numbness of the area), surgical excision (removal of cancer with surrounding normal tissue margin), tissue examination (sent to pathology to confirm complete removal), wound closure (layered closure to minimize scarring and optimize cosmetic result), and pathology confirmation (margin status reported to ensure complete removal). MARGINS: Different cancers require different safety margins, typically 3-5mm for low-risk basal cell carcinoma, 4-10mm for squamous cell carcinoma depending on risk factors, wider margins for melanoma based on depth. RECONSTRUCTION: Simple side-to-side closure for many excisions, flaps or grafts for larger defects, careful planning to follow natural skin lines and minimize visible scarring, and specialized techniques for cosmetically sensitive areas. Cure rates with appropriate surgical excision are excellent when cancer is caught early.",
        },
        {
          title: "Removal of Benign Lesions",
          content:
            "Many non-cancerous skin growths can be bothersome, symptomatic, or cosmetically concerning. Dr. Nkehli performs removal of various benign lesions using appropriate surgical techniques. COMMONLY REMOVED BENIGN LESIONS: Moles (nevi) that are changing, irritated, or cosmetically bothersome, Seborrheic keratoses (benign warty growths common with aging), Skin tags (small flesh-colored stalks in friction areas), Dermatofibromas (firm nodules often on legs), Lipomas (benign fatty lumps under skin), Epidermoid and pilar cysts (fluid-filled sacs that can become infected), Pyogenic granulomas (rapidly growing vascular nodules), and Cherry angiomas (red vascular spots). REMOVAL TECHNIQUES: Shave excision (for raised lesions, minimal to no scarring), Excision with closure (for deeper or larger lesions, results in linear scar), Electrocautery (burning technique for superficial lesions), Cryotherapy (freezing for some lesions), and Cyst removal (complete excision of cyst wall to prevent recurrence). INDICATIONS FOR REMOVAL: Suspicion of malignancy requiring biopsy, symptomatic lesions (painful, bleeding, itching), cosmetic concerns, lesions in areas of frequent trauma or irritation, and patient preference. While many benign lesions don't medically require removal, Dr. Nkehli understands that cosmetic concerns are valid and offers removal with techniques that optimize cosmetic outcomes.",
        },
        {
          title: "Cyst Removal",
          content:
            "Epidermoid cysts and pilar cysts are common benign growths that can become problematic. Proper surgical removal prevents recurrence. ABOUT CYSTS: Sac beneath skin filled with keratin material, often have visible central punctum (pore), can remain stable for years or slowly enlarge, prone to infection and rupture causing inflammation, unpleasant odor if contents expressed, and tend to recur if not completely removed. SURGICAL REMOVAL: Performed when not actively infected (infected cysts first drained and treated with antibiotics, then removed once healed), local anesthesia injection around cyst, incision made over cyst, careful dissection to remove entire cyst wall intact, if wall left behind, cyst likely to recur, closure with stitches, and removal of stitches in 1-2 weeks. INFECTED CYSTS: Incision and drainage (I&D) to release pus and relieve pain, oral antibiotics, warm compresses at home, and definitive surgical removal 4-6 weeks after infection resolves. POST-OPERATIVE CARE: Keep area clean and dry, watch for signs of infection, suture removal in 7-14 days depending on location, and minimal scarring once fully healed. Complete cyst removal with intact cyst wall provides the best chance of preventing recurrence and eliminates the risk of future infections.",
        },
        {
          title: "Electrocautery and Curettage",
          content:
            "Electrodesiccation and curettage (ED&C) is a technique combining scraping (curettage) and burning (electrocautery) to remove skin lesions. This procedure is effective for certain types of skin cancers and benign lesions. SUITABLE LESIONS: Superficial basal cell carcinomas in low-risk locations, seborrheic keratoses, warts resistant to other treatments, actinic keratoses (precancerous lesions), and some other benign growths. THE PROCEDURE: Local anesthesia injection, curettage (scraping away abnormal tissue with sharp curette), electrocautery (destroying any remaining abnormal cells), typically repeated 2-3 times, hemostasis (stopping any bleeding), and healing by secondary intention (wound heals from base upward, no stitches needed). HEALING: Initial scab formation over treated area, gradual healing over 2-4 weeks, gentle wound care with petrolatum ointment, avoid picking at scab, and once healed, may have slight color or texture difference. ADVANTAGES: No stitches required, quick procedure, effective for appropriate lesions, and cure rates of 90-95% for properly selected basal cell carcinomas. This technique is detailed in our Electrocautery service page for more information about specific applications, healing, and expected outcomes.",
        },
        {
          title: "Cryosurgery",
          content:
            "Cryosurgery uses liquid nitrogen to freeze and destroy abnormal tissue. This is an effective treatment for various benign and precancerous lesions. COMMONLY TREATED: Actinic keratoses (precancerous sun damage spots), warts (viral lesions), seborrheic keratoses (benign age-related growths), small superficial skin cancers in selected cases, and various other benign lesions. THE PROCEDURE: Liquid nitrogen applied with spray device or cotton-tipped applicator, intense cold (-196°C) destroys targeted tissue, stinging or burning sensation during treatment (lasts seconds to minutes), no anesthesia typically needed for small lesions, and total treatment time usually under a minute per lesion. HEALING: Blister may form within hours to days, gradual healing over 1-3 weeks, crust or scab formation, possible temporary pigment change (especially in darker skin), and some lesions require repeat treatment. ADVANTAGES: Quick procedure, no cutting or stitches, multiple lesions treated in one visit, and effective for appropriate lesions. For detailed information about cryosurgery, indications, healing process, and what to expect, see our dedicated Cryosurgery service page.",
        },
        {
          title: "Scar Revision and Keloid Treatment",
          content:
            "Some scars become problematic, either from excessive growth (keloids and hypertrophic scars) or cosmetically unfavorable appearance. Dr. Nkehli offers treatments to improve problematic scarring. KELOIDS AND HYPERTROPHIC SCARS: Keloids extend beyond original wound boundaries, hypertrophic scars stay within wound but raised, both result from excessive collagen production, genetic predisposition in some individuals, and common on chest, shoulders, ears, and upper back. TREATMENT OPTIONS: Intralesional corticosteroid injections (flatten and soften raised scars, repeated monthly or every 6 weeks, very effective for many keloids), Surgical excision (removal followed by preventive measures, combined with other treatments to prevent recurrence), Cryotherapy (freezing to reduce scar tissue), Pressure therapy (specialized dressings or earrings for earlobe keloids), and Silicone gel sheets (over-the-counter option for scar management). SCAR REVISION: Surgical techniques to reorient scar with skin tension lines, Z-plasty or W-plasty techniques, staged procedures for large scars, and dermabrasion or laser therapy in some cases. Managing keloids and hypertrophic scars requires patience and often combination therapy, but significant improvement is possible with appropriate treatment.",
        },
        {
          title: "What to Expect During Your Surgical Procedure",
          content:
            "Understanding what to expect helps reduce anxiety and ensures the best outcome. BEFORE THE PROCEDURE: Discussion of procedure, risks, benefits, and alternatives, informed consent signed, photos for medical record when appropriate, area cleaned and marked, and local anesthesia injected (brief stinging, then numbness). DURING THE PROCEDURE: You remain awake and comfortable, procedure typically painless once area is numb, Dr. Nkehli explains what she is doing, you can ask questions during procedure, and most procedures completed in 15-30 minutes. AFTER THE PROCEDURE: Pressure applied if needed to control bleeding, wound dressed appropriately, written aftercare instructions provided, prescription for pain medication if needed (usually just acetaminophen), and activity restrictions discussed. Most patients drive themselves home and return to normal activities the same day or next day with only minor modifications. You will be scheduled for follow-up to check healing, remove stitches if needed, and discuss pathology results.",
        },
        {
          title: "Post-Operative Care and Healing",
          content:
            "Proper wound care is essential for optimal healing and cosmetic outcome. Dr. Nkehli provides detailed instructions specific to your procedure. GENERAL WOUND CARE: Keep area clean and dry for first 24-48 hours, gently cleanse with mild soap and water after initial period, apply prescribed ointment (usually petroleum jelly or antibiotic ointment), cover with bandage as instructed, and change dressing daily or as directed. ACTIVITY RESTRICTIONS: Avoid strenuous exercise for period specified (usually 3-7 days), limit movements that pull on wound, protect surgical site from sun exposure, avoid swimming or soaking until fully healed, and no heavy lifting if on trunk or extremities. SIGNS TO WATCH FOR: Excessive bleeding (small amount on dressing is normal), increasing pain, redness, warmth, or swelling (possible infection), fever, wound separation, and pus or foul drainage. Contact our office immediately if you experience any concerning symptoms. SUTURE REMOVAL: Timing depends on location (face 5-7 days, scalp 7-10 days, trunk and extremities 10-14 days), brief appointment, minimal to no discomfort, and scar continues to mature for months after suture removal. Scars are typically red or pink initially, gradually fade over 6-12 months, can be camouflaged with makeup once healed, and sunscreen essential to prevent hyperpigmentation. Following post-operative instructions carefully ensures the best possible outcome.",
        },
        {
          title: "Why Choose Dr. Nkehli for Surgical Dermatology?",
          content:
            "Surgical dermatology requires both medical expertise and surgical skill. Dr. Nkehli offers the highest level of both. SPECIALIZED TRAINING: Completed dermatology residency with extensive surgical training, expert knowledge of skin anatomy and structure, understanding of skin healing and scar formation, experience with techniques that minimize scarring, and continued education in latest surgical advances. COMPREHENSIVE APPROACH: Accurate diagnosis before surgical intervention, appropriate procedure selection for each condition, consideration of cosmetic outcome in every case, realistic expectations discussed upfront, and complete post-operative care and monitoring. IN-OFFICE CONVENIENCE: Most procedures performed in comfortable office setting, no hospital visit or general anesthesia required, minimal disruption to your schedule, and immediate access to Dr. Nkehli for any concerns. PATIENT-CENTERED CARE: Thorough explanation of procedures and expectations, attention to your concerns and questions, gentle technique with focus on comfort, transparent discussion of risks and benefits, and personalized post-operative care instructions. Dr. Nkehli's combination of dermatologic medical expertise and refined surgical skills ensures you receive optimal outcomes with the smallest possible scars and lowest risk of complications.",
        },
        {
          title: "Scheduling Your Surgical Consultation",
          content:
            "If you have a concerning skin lesion or need a surgical dermatology procedure, schedule a consultation with Dr. Nkehli. CONSULTATION PROCESS: Evaluation of your skin condition or lesion, discussion of diagnosis or differential diagnosis, recommendation for biopsy or treatment, explanation of surgical procedure if indicated, discussion of expected outcome and potential risks, and time for all your questions. PREPARING FOR SURGERY: Some procedures can be performed same day as consultation, others scheduled for separate surgical appointment, arrive with clean skin (no makeup if facial procedure), wear comfortable clothing with easy access to area, arrange for driver if you prefer (though most patients drive themselves), and list of current medications reviewed. PRICING: Consultation fees apply, surgical procedure pricing discussed during consultation, dependent on complexity and extent of procedure, pathology fees may apply separately, and medical insurance may cover procedures performed for medical (not cosmetic) indications. Contact Dermaglare Skin today to schedule your surgical dermatology consultation. Dr. Nkehli will evaluate your condition and recommend the most appropriate treatment to address your concerns with optimal medical and cosmetic outcomes.",
        },
      ]}
      features={[
        "Skin Cancer Excision",
        "Diagnostic Biopsies",
        "Cyst Removal",
        "Benign Lesion Removal",
        "Electrocautery & Curettage",
        "Cryosurgery",
        "Scar Revision",
        "Keloid Treatment",
      ]}
    />
  );
}
